package gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MainPanel extends JFrame {

    public JPanel MainP;
    private JPanel leftPanel;
    private JPanel rightPanel;
    private JTextField txtToX;
    private JTextField txtToY;
    private JButton btnDrive;
    private JButton btnM_Drive;
    private JTextField txtFromX;
    private JTextField txtFromY;

    public MainPanel() {
        super("");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setContentPane(MainP);
        setResizable(false);
        pack();

        setVisible(true);
        btnDrive.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Main.conn.sendData(Integer.parseInt(txtFromX.getText()));
                    Main.conn.sendData(Integer.parseInt(txtFromY.getText()));
                    Main.conn.sendData(Integer.parseInt(txtToX.getText()));
                    Main.conn.sendData(Integer.parseInt(txtToY.getText()));
                } catch (IllegalArgumentException ex) {
                    JOptionPane.showMessageDialog(new JFrame(""), "Ongeldige invoer");
                }
            }
        });

        btnM_Drive.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Main.conn.sendData(254);
                new ManualDrive();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        MainP = new JPanel();
        MainP.setLayout(new BorderLayout(0, 0));
        MainP.setMinimumSize(new Dimension(375, 135));
        MainP.setOpaque(true);
        MainP.setPreferredSize(new Dimension(375, 135));
        leftPanel = new JPanel();
        leftPanel.setLayout(new BorderLayout(0, 0));
        MainP.add(leftPanel, BorderLayout.WEST);
        leftPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Rijden over grid"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        leftPanel.add(panel1, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2);
        final JLabel label1 = new JLabel();
        label1.setPreferredSize(new Dimension(35, 35));
        label1.setText("Naar:");
        panel2.add(label1);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel3);
        final JLabel label2 = new JLabel();
        label2.setText("X:");
        panel3.add(label2);
        txtToX = new JTextField();
        txtToX.setMinimumSize(new Dimension(40, 35));
        txtToX.setPreferredSize(new Dimension(40, 35));
        panel3.add(txtToX);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel4);
        final JLabel label3 = new JLabel();
        label3.setText("Y");
        panel4.add(label3);
        txtToY = new JTextField();
        txtToY.setMinimumSize(new Dimension(40, 35));
        txtToY.setPreferredSize(new Dimension(40, 35));
        panel4.add(txtToY);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        leftPanel.add(panel5, BorderLayout.NORTH);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel5.add(panel6);
        final JLabel label4 = new JLabel();
        label4.setPreferredSize(new Dimension(28, 35));
        label4.setText("Van:");
        panel6.add(label4);
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel5.add(panel7);
        final JLabel label5 = new JLabel();
        label5.setText("X:");
        panel7.add(label5);
        txtFromX = new JTextField();
        txtFromX.setMinimumSize(new Dimension(40, 35));
        txtFromX.setPreferredSize(new Dimension(40, 35));
        panel7.add(txtFromX);
        final JPanel panel8 = new JPanel();
        panel8.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel5.add(panel8);
        final JLabel label6 = new JLabel();
        label6.setText("Y:");
        panel8.add(label6);
        txtFromY = new JTextField();
        txtFromY.setMinimumSize(new Dimension(40, 35));
        txtFromY.setPreferredSize(new Dimension(40, 35));
        panel8.add(txtFromY);
        rightPanel = new JPanel();
        rightPanel.setLayout(new GridBagLayout());
        MainP.add(rightPanel, BorderLayout.CENTER);
        final JPanel panel9 = new JPanel();
        panel9.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        rightPanel.add(panel9, gbc);
        btnDrive = new JButton();
        btnDrive.setText("Rij route");
        panel9.add(btnDrive);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        rightPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        rightPanel.add(spacer2, gbc);
        final JPanel panel10 = new JPanel();
        panel10.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        rightPanel.add(panel10, gbc);
        btnM_Drive = new JButton();
        btnM_Drive.setText("Handmatige beturing");
        panel10.add(btnM_Drive);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return MainP;
    }
}
